version: '3'

services:
  api-server:
    build: .
    ports:
      - "5000:5000"
    container_name: api-server

  api-client:
    image: python:3.10
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - api-server
    command: bash -c "pip install requests && python api_client.py"
